imports:
    - { resource: parameters.yml }

services:
    roots.discordnotifications.notification_service:
        class: roots\discordnotifications\notification_service
        arguments:
            - '@config'
            - '@config_text'
            - '@user'

    roots.discordnotifications.listener:
        class: roots\discordnotifications\event\notification_event_listener
        arguments:
            - '@roots.discordnotifications.notification_service'
        tags:
            - { name: event.listener }
